### ISSUE TITLE
Can't install due to `npm ERR! must provide string spec`

### ISSUE THREAD

**Issue by insanity54** [0dataapp/0data#2]
After I cloned this repo, I ran `npm install` and saw the following error

```
chris@ti83plus:~/Documents/0data$ npm install
npm ERR! must provide string spec

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chris/.npm/_logs/2021-03-06T10_40_28_963Z-debug.log
```

```
cchris@ti83plus:~$ cat /home/chris/.npm/_logs/2021-03-06T10_40_28_963Z-debug.log
0 verbose cli [
0 verbose cli   '/home/chris/.nvm/versions/node/v15.5.0/bin/node',
0 verbose cli   '/home/chris/.nvm/versions/node/v15.5.0/bin/npm',
0 verbose cli   'install'
0 verbose cli ]
1 info using npm@7.3.0
2 info using node@v15.5.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/home/chris/.nvm/versions/node/v15.5.0/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 0ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/chris/Documents/0data/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/home/chris/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/home/chris/.nvm/versions/node/v15.5.0/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 verbose npm-session 6714758f31536e68
20 timing npm:load Completed in 10ms
21 timing arborist:ctor Completed in 0ms
22 timing idealTree Completed in 7ms
23 timing command:install Completed in 8ms
24 verbose stack TypeError: must provide string spec
24 verbose stack     at new Edge (/home/chris/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/edge.js:32:13)
24 verbose stack     at Node.[_loadDepType] (/home/chris/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:756:9)
24 verbose stack     at Node.[Arborist.Node._loadDeps] (/home/chris/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:724:23)
24 verbose stack     at new Node (/home/chris/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:228:20)
24 verbose stack     at Arborist.[rootNodeFromPackage] (/home/chris/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:347:12)
24 verbose stack     at /home/chris/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:290:42
24 verbose stack     at async Arborist.buildIdealTree (/home/chris/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:206:7)
24 verbose stack     at async Promise.all (index 1)
24 verbose stack     at async Arborist.reify (/home/chris/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:123:5)
24 verbose stack     at async install (/home/chris/.nvm/versions/node/v15.5.0/lib/node_modules/npm/lib/install.js:38:3)
25 verbose cwd /home/chris/Documents/0data
26 verbose Linux 5.8.0-7630-generic
27 verbose argv "/home/chris/.nvm/versions/node/v15.5.0/bin/node" "/home/chris/.nvm/versions/node/v15.5.0/bin/npm" "install"
28 verbose node v15.5.0
29 verbose npm  v7.3.0
30 error must provide string spec
31 verbose exit 1
```

**Comment by insanity54** [comment]
I think this is caused by a bug in npm. Using [nvm](https://github.com/nvm-sh/nvm) I downgraded to v6.14.11 and I was able to install.
